### ISSUE TITLE
서버리스에서 배포가 되지 않는 문제

### ISSUE THREAD

**Issue by nabi-chan** [nabi-chan-archive/blog-2021#4]
`yarn build` 명령어를 실행했을 때 다음과 같은 오류가 발생함

```
TypeError: debugLib is not a function
    at Object.<anonymous> (/Users/pinot/WebstormProjects/blog/.next/serverless/pages/index.js:5101:15)
    at Object.6Z5O (/Users/pinot/WebstormProjects/blog/.next/serverless/pages/index.js:5294:30)
    at __webpack_require__ (/Users/pinot/WebstormProjects/blog/.next/serverless/pages/index.js:23:31)
    at Object.<anonymous> (/Users/pinot/WebstormProjects/blog/.next/serverless/pages/index.js:46580:65)
    at Object.Kg+b (/Users/pinot/WebstormProjects/blog/.next/serverless/pages/index.js:46592:30)
    at __webpack_require__ (/Users/pinot/WebstormProjects/blog/.next/serverless/pages/index.js:23:31)
    at Object.tBZW (/Users/pinot/WebstormProjects/blog/.next/serverless/pages/index.js:82086:72)
    at __webpack_require__ (/Users/pinot/WebstormProjects/blog/.next/serverless/pages/index.js:23:31)
    at Module.QeBL (/Users/pinot/WebstormProjects/blog/.next/serverless/pages/index.js:49801:69)
    at __webpack_require__ (/Users/pinot/WebstormProjects/blog/.next/serverless/pages/index.js:23:31) {
  type: 'TypeError'
}
```

**Comment by nabi-chan** [comment]
이미 Prisma에 비슷한 내용의 이슈가 있는 듯 하다.

https://github.com/prisma/prisma/issues/6032

**Comment by nabi-chan** [comment]
## 새로운 시도
Upgrade `prisma` and `@prisma/client` version to 2.22.1

Ref: https://answers.netlify.com/t/netlify-wont-deploy-my-next-js-prisma-app/34716/5

**Comment by nabi-chan** [comment]
It works!

<img width="516" alt="image" src="https://user-images.githubusercontent.com/42037851/117881898-bb530580-b2e4-11eb-88b4-0820aa136c3d.png">
